name: "Prepare for Develop"

on:
  pull_request: 
    types:
      - synchronize
      - opened

jobs:
  unit-tests:
    uses: ./.github/workflows/jobs/UnitTests.yml
    secrets: inherit 

  build-project:
    needs: unit-tests
    uses: ./.github/workflows/jobs/BuildGame.yml
    secrets: inherit
    