name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  unit-tests:
    uses: ./.github/workflows/UnitTests.yml
    secrets: inherit 

  build-project:
    needs: unit-tests
    uses: ./.github/workflows/BuildGame.yml
    secrets: inherit